spring.application.name=mongobank

#Database
# spring.datasource.url = mongodb+srv://daphnecluseau_db_user:j1QEkcrWNUyBB9uk@cluster0.uqykaj2.mongodb.net/
# spring.datasource.driver-class-name=mongodb.jdbc.MongoDriver
# spring.mongodb.uri=mongodb+srv://daphnecluseau_db_user:j1QEkcrWNUyBB9uk@cluster0.uqykaj2.mongodb.net/
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=mongobank

# spring.main.allow-bean-definition-overriding=true